### ISSUE TITLE
2 Pop up errors

### ISSUE THREAD

**Issue by RoldanLT** [vbresults/mobile-apps-for-xenforo#11]
I encounter this yesterday, with previous app/addon version. I after this 2 pop ups, browser hangs up and not usable.

http://i.imgur.com/AnOWLnX.png
http://i.imgur.com/qIlDzoJ.png

**Comment by vbresults** [comment]
Fixed in the latest version

**Comment by RoldanLT** [comment]
I have to disable the addon for now because of this new pop up error.

http://i.imgur.com/4gpIuad.png

**Comment by RoldanLT** [comment]
That error just happen to me last few minutes.
You must have changed something on the back-end? 
Thanks for the quick response.

**Comment by vbresults** [comment]
If you clear app data is it fixed?

**Comment by RoldanLT** [comment]
Force stop, clear data > no pop up error.
I think that error only appear when you have unread alerts.

**Comment by RoldanLT** [comment]
Not happening again for me, even with unread/new alerts.
You did some changes right? :)
Thanks!
Still no push notifications for me Android 4.1.2 :(.

**Comment by vbresults** [comment]
Send a PM to testuser123

**Comment by RoldanLT** [comment]
Done (y).

**Comment by RoldanLT** [comment]
The 2 errors happen again on Mobile browsers :(.

**Comment by vbresults** [comment]
Is their cache cleared?

**Comment by RoldanLT** [comment]
Yes I cleared last 25 mins: https://github.com/vbresults/mobile-apps-for-xenforo/issues/11#issuecomment-156771466

**Comment by vbresults** [comment]
What browser?

**Comment by RoldanLT** [comment]
Default Samsung Browser.

(I disabled the addon for now as guest can't visit my site for that error).

**Comment by vbresults** [comment]
Please turn it back on for 15 minutes so we can fix and confirm

**Comment by RoldanLT** [comment]
Turn on now.
By the way, I have Guest view Nginx fastcgi Full Page caching for 10 minutes.
So guest will update next 10 minutes also.

**Comment by RoldanLT** [comment]
To bypass Guest Full page cache, please visit a random thread. Very OLD thread mostly not cached.
Like: http://www.phcorner.net/t/555/

**Comment by vbresults** [comment]
Found an fixed the popup problem

**Comment by RoldanLT** [comment]
How to apply the fix Sir?
Thanks!

**Comment by vbresults** [comment]
Nothing for you to do, this is fixed on our CDN and your page cache doesn't cause a problem since it's our CDN

**Comment by vbresults** [comment]
Confirmed fixed looks like we don't have to clear browser cache, and it revealed a bug in the custom style detection too but that's not as urgent as the push issue reported, looking into that now

**Comment by vbresults** [comment]
Ah wait, it's not taking effect, looks like I do have to clear cache

**Comment by vbresults** [comment]
Please open a separate issue for the alerts

**Comment by RoldanLT** [comment]
And it's fixed already now?
Cause I still seeing it on every pages I visit on the site.
I can even replicate it as login member and just use Desktop Browser with Android user agent :|.

**Comment by RoldanLT** [comment]
http://i.imgur.com/MlYlxSW.png
http://i.imgur.com/utY4P8D.png

**Comment by RoldanLT** [comment]
And not receiving pop error now.

**Comment by RoldanLT** [comment]
After this commnet: https://github.com/vbresults/mobile-apps-for-xenforo/issues/11#issuecomment-156775357
What changes have been made?
Seems fine now.

**Comment by RoldanLT** [comment]
By the way, I'm still receiving this on Default browser of Samsung :(.

**Comment by vbresults** [comment]
This shouldn't be in the code anymore, is it from the cache, or already cleared?

**Comment by RoldanLT** [comment]
I already cleared all my phone Default Browser Data, Cache, Cookies.

**Comment by vbresults** [comment]
Sent you a message on the forum again

**Comment by RoldanLT** [comment]
Now 5 error pop ups: https://www.phcorner.net/t/help-mga-k-ph.107846/#post-849135
I have to disable the addon.
